// User
const FIRST_NAME_MIN_LENGTH = 2;
const FIRST_NAME_MAX_LENGTH = 20;
const LAST_NAME_MIN_LENGTH = 2;
const LAST_NAME_MAX_LENGTH = 20;
const PASSWORD_MIN_LENGTH = 6;
const PASSWORD_MAX_LENGTH = 70;
const EMAIL_REGEX = /^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/;

// Image
const MAX_FILE_UPLOAD_SIZE_IN_BYTES = 1500000; // 1.5MB
const FILE_EXT_REGEX = /jpeg|jpg|png|gif/; // regular expression

// Vacation
const VACATION_TITLE_MIN_LENGTH = 2;
const VACATION_TITLE_MAX_LENGTH = 40;
const VACATION_DESTINATION_MIN_LENGTH = 2;
const VACATION_DESTINATION_MAX_LENGTH = 40;

module.exports = {
  FIRST_NAME_MIN_LENGTH,
  FIRST_NAME_MAX_LENGTH,
  LAST_NAME_MIN_LENGTH,
  LAST_NAME_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  EMAIL_REGEX,
  MAX_FILE_UPLOAD_SIZE_IN_BYTES,
  FILE_EXT_REGEX,
  VACATION_TITLE_MIN_LENGTH,
  VACATION_TITLE_MAX_LENGTH,
  VACATION_DESTINATION_MIN_LENGTH,
  VACATION_DESTINATION_MAX_LENGTH
}